// The content pipeline. This is where the game's levels come from — the browser never
// generates a lot, it only picks one.
//
// Why offline: test/balance.mjs measures the generator at 3.6 s median and 18 s worst
// case for the top tier, with only a few in twenty seeds producing a lot at all. That is
// a perfectly good cost for a build step and an unacceptable one for a tap on the screen.
// So the generator runs here once, the solver certifies every lot it emits, and what
// ships is the measured set.
//
//   node tools/bake.mjs                 # js/data/lots.js
//   PER_TIER=24 node tools/bake.mjs
//
// A lot only enters the file if re-solving the *serialised* spec reproduces the move
// count the generator claimed. Nothing unmeasured ships.

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { TIERS, makeLot } from '../js/core/make.js';
import { solve, census } from '../js/core/solve.js';
import { validate, toSpec } from '../js/core/lot.js';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const PER_TIER = Number(process.env.PER_TIER || 16);

// Two lots that differ only in the order their cars were appended are the same puzzle.
function signature(spec) {
  const cars = spec.cars
    .map((c) => `${c.axis}${c.x},${c.y}+${c.len}${c.hero ? '!' : ''}`)
    .sort()
    .join('|');
  return `${spec.w}x${spec.h}:${spec.exitRow}:${cars}`;
}

const out = [];
for (const tier of TIERS) {
  const seen = new Set();
  const picked = [];
  const t0 = Date.now();
  for (let s = 0; picked.length < PER_TIER && s < PER_TIER * 60; s++) {
    const lot = makeLot(`bake-${tier.key}-${s}`, tier);
    if (!lot) continue;
    const spec = toSpec(lot.spec.comp, lot.spec.comp.start);
    const err = validate(spec);
    if (err) throw new Error(`${tier.key}: generator emitted an invalid lot: ${err}`);
    const sig = signature(spec);
    if (seen.has(sig)) continue;
    const again = solve(spec);
    if (!again.ok || again.moves !== lot.rating.moves) {
      throw new Error(`${tier.key}: par ${lot.rating.moves} not reproducible from the spec (${again.moves})`);
    }
    seen.add(sig);
    picked.push({
      id: `${tier.key}-${String(picked.length + 1).padStart(2, '0')}`,
      tier: tier.key,
      moves: again.moves,
      states: census(spec, 300000).states,
      cars: spec.cars.length,
      spec,
    });
    process.stdout.write(`\r${tier.key}: ${picked.length}/${PER_TIER}  ${((Date.now() - t0) / 1000).toFixed(0)}s   `);
  }
  process.stdout.write(`\n`);
  if (picked.length < PER_TIER) console.error(`warn: ${tier.key} only reached ${picked.length} lots`);
  // A tier is played as a curve, so order it by the one number that means something.
  picked.sort((a, b) => a.moves - b.moves || a.states - b.states);
  picked.forEach((p, i) => { p.id = `${tier.key}-${String(i + 1).padStart(2, '0')}`; });
  out.push(...picked);
}

// The band the UI prints is measured off the lots that actually shipped, not copied from
// the generator's wish list — so a re-bake that lands lighter or heavier says so.
const meta = TIERS.map((t) => {
  const mine = out.filter((l) => l.tier === t.key).map((l) => l.moves);
  const lo = Math.min(...mine);
  const hi = Math.max(...mine);
  return {
    key: t.key, label: t.label, min: lo, max: hi,
    blurb: `${t.w}×${t.h} · ${lo === hi ? lo : `${lo}-${hi}`} 步`,
  };
});
const lines = [
  '// Generated by tools/bake.mjs — the levels in this game are measurements, not opinions.',
  '// `moves` is the BFS-shortest drag count for the spec on the same line; re-run',
  '// `node tools/bake.mjs` instead of hand-editing, and `node test/library.test.mjs`',
  '// will fail if a line and its number ever disagree.',
  `export const TIERS_META = ${JSON.stringify(meta)};`,
  'export const LOTS = [',
  ...out.map((l) => `  ${JSON.stringify(l)},`),
  '];',
  '',
];
const path = join(root, 'js', 'data', 'lots.js');
mkdirSync(dirname(path), { recursive: true });
writeFileSync(path, lines.join('\n'));

const byTier = {};
for (const l of out) byTier[l.tier] = (byTier[l.tier] || 0) + 1;
console.log(`wrote ${out.length} lots (${Object.entries(byTier).map(([k, n]) => `${k}:${n}`).join(' ')}) -> js/data/lots.js`);
